version: '3.8'

services:
  web:
    build: .
    command: >
      sh -c "python3 generate_cert.py &&
             python3 manage.py makemigrations dsapp &&
             python3 manage.py flush --noinput &&  
             python3 manage.py migrate &&
             python3 manage.py loaddata status.json &&
             python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - "5432:5432"
volumes:
  postgres_data: